# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/penguin04172"

[social.params]
icon = "brand-github"

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://facebook.com/penguin04172"

[social.params]
icon = "brand-facebook"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://instagram.com/penguin04172"

[social.params]
icon = "brand-instagram"
